language: python
python:
  - "3.7"
services:
  - docker
before_install:
  - docker pull xinyaanzyoy/pipelinetest2351:latest
  - docker run pipelinetest2351
script: cd /Xbooks/ && source activate Xbooks_env && python Xbooks.py $REPO $PAT