image:
    file: .gitpod.dockerfile
ports:
- port: 8888
  onOpen: open-browser
- port: 8080
  onOpen: notify
tasks:
- command: npm i -g npm && ((rm -r node_modules && rm -f package-lock.json && npm i && npm i -g ./) || npm i && npm i -g ./)
- command: conda activate base && jupyter notebook notebooks/ --NotebookApp.allow_origin=\'$(gp url 8888)\' --ip='*' --NotebookApp.token='' --NotebookApp.password=''