ports:
- port: 8888
  onOpen: open-preview
- port: 1969
  onOpen: open-browser
- port: 1905
  onOpen: ignore
- port: 8080
  onOpen: notify
tasks:
- command: npm i -g npm && rm -r node_modules && rm -f package-lock.json && npm i && npm i -g ./
- command: pyenv uninstall 2.7.15 --force && pyenv uninstall 3.7.2 --force && pyenv install anaconda3-5.3.1 && pyenv global anaconda3-5.3.1