version: 2
jobs:
  build:
    docker:
      - image: xsoft/xbooks:latest
    steps:
      - run:
          name: Xbooks_Transformation
          command: cd /Xbooks/ && source activate Xbooks_env && python Xbooks.py $REPO $GH_TOKEN
  deploy:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: 
          name: Dependencies_Installation
          command: npm i
      - run: 
          name: Versioning
          command: npx semantic-release
