version: 2
jobs:
  Xbooks_Transformation:
    filters:
      branches:
        only: master
    docker:
      - image: xsoft/xbooks:latest
    steps:
      - run:
          name: running_Xbooks_Container_App
          command: cd /Xbooks/ && source activate Xbooks_env && python script.py $REPO $GH_TOKEN
  Semantic_Versioning:
    filters:
      branches:
        only: master
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: 
          name: Dependencies_Installation
          command: npm i
      - run: 
          name: Versioning
          command: npx semantic-release
workflows:
  version: 2
  build:
    jobs:
      - Xbooks_Transformation
      - Semantic_Versioning
