stages:
    - deploy

image: xsoft/xbooks

before_script:
    - git pull https://$AUTHOR$:$PAT@github.com/$AUTHOR$/$REPO$.git master
    - git checkout master

transformation:
    stage: deploy
    script:
        - pwd