variables:
  GIT_STRATEGY: none

stages:
    - deploy

image: xsoft/xbooks:latest

Xbooks_Transformation:
    stage: deploy
    script:
        - cd /Xbooks/ && source activate Xbooks_env && python Xbooks.py $REPO $PAT