version: 2
jobs:
  Xbooks_Transformation:
    filters:
      branches:
        only: master
    docker:
      - image: xsoft/xbooks:latest
    steps:
      - run:
          name: running_Xbooks_Container_App
          command: cd /Xbooks/ && source activate Xbooks_env && python Xbooks.py $REPO $GH_TOKEN
workflows:
  version: 2
  build:
    jobs:
      - Xbooks_Transformation